### ISSUE TITLE
Pretrained models-download script

### ISSUE THREAD

**Issue by pegah-kh** [vita-epfl/motion-style-transfer#2]
Hello,
The 'get pretrained and data' script does not result in the folder structure as explained in the ReadMe. Such as: under the filter directory, there is no long term and short term. Would you please more information if the structure is different from what is explained in ReadMe, or change the structure of folders itself?

**Comment by theDebugger811** [comment]
Hello @Pegah-source ,
       The directory structure should be followed now.

Closing the issue. Re-open if any other concern arises
